site_name: DigiStokvel

theme:
  name: material
  features:
    - search.highlight
    - search.exact_match
    - navigation.tabs
    - toc.integrate

nav:
  - Home: index.md
  - System Architecture:
    - Overview: system-architecture/overview.md
  - Components:
      - Database: components/database.md
      - Flask : components/flask.md
      - Express: components/express.md
      - Flask Templates: components/flask_templates.md
      - Function App: components/function_app.md
  - Devops:
      - Overview: devops/overview.md
      - Git Management: devops/git.md
      - Docker: devops/docker.md
      - Terraform: devops/terraform.md


markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.superfences


extra_css:
  - stylesheets/extra.css


