site_name: DigiStokvel

theme:
  name: material
  features:
    - search.highlight
    - search.exact_match
    - navigation.tabs
    - toc.integrate

nav:
  - Home: index.md
  - System Architecture:
    - Overview: system-architecture/overview.md
  - Components:
      - Overview: architecture/overview.md
      - Database: architecture/database.md
      - Terraform: architecture/terraform.md
      - Docker: architecture/docker.md
      - Flask Templates: architecture/flask_templates.md
      - Components: architecture/components.md
      - Testing: architecture/testing.md
  - Devops:
      - Overview: devops/overview.md
      - Docker: devops/docker.md


markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.superfences


extra_css:
  - stylesheets/extra.css


