site_name: DigiStokvel

theme:
  name: material
  features:
    - search.highlight
    - search.exact_match
    - navigation.tabs
    - toc.integrate

nav:
  - Home: index.md
  - API:
      - Overview: api/overview.md
      - Endpoints: api/endpoints.md

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.superfences

extra_css:
  - stylesheets/extra.css
