openapi: 3.0.0
info:
  title: Rafiki Exchange Rates
  version: '1.0'
  license:
    name: Apache 2.0
    identifier: Apache-2.0
  summary: Integration Endpoint Rafiki expects at the Account Servicing Entity
  description: 'Rafiki calls this endpoint at the Account Servicing Entity in order to fetch current exchange rates.'
  contact:
    email: tech@interledger.org
servers:
  - url: 'http://127.0.0.1:5000'
tags:
  - name: rates
    description: Exchange rates
paths:
  /rates:
    parameters:
      - schema:
          type: string
          minLength: 1
        name: base
        in: query
        required: true
        description: Base exchange rate Base exchange rate
    get:
      summary: Fetch exchange rates
      operationId: get-rates
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rates'
              examples:
                USD Exchange Rates:
                  value:
                    base: 'USD'
                    rates:
                      EUR: 1.1602
                      ZAR: 17.3792
                ZAR Exchange Rates:
                  value:
                    base: 'ZAR'
                    rates:
                      USD: 0.0575
                      EUR: 0.0667
        '404':
          description: Not Found
      description: Fetch current exchange rate pairs.
      tags:
        - rates
components:
  schemas:
    rates:
      title: rates
      type: object
      properties:
        base:
          type: string
        rates:
          type: object
          patternProperties:
            ^[A-Z]{3}$:
              type: number
      required:
        - base
        - rates
  securitySchemes: {}
security: []