name: Cleanup Temporary Branch

on:
  workflow_run:
    workflows: ["Lint and Test"]
    types:
      - completed

jobs:
  cleanup:
    runs-on: ubuntu-latest
    if: always()  # Always run the cleanup job
    steps:
      - name: Download branch name artifact
        uses: actions/download-artifact@v3
        with:
          name: branch_name
          path: .

      - name: Read branch name
        id: read-branch
        run: |
          BRANCH_NAME=$(cat branch_name.txt)
          echo "Branch to delete: $BRANCH_NAME"
          echo "branch_name=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Delete temporary branch
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git push origin --delete ${{ env.branch_name }} || true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
