name: CI Pipeline

on:
  pull_request:
    branches:
      - main

permissions:
  contents: write  # Allows pushing changes back to the PR branch

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pylint mypy black isort
      
      - name: Run Isort
        run: isort .

      - name: Run Black
        run: black .

      - name: Run Flake8
        run: flake8 .

      - name: Run Pylint
        run: pylint --recursive=y --fail-under=9.7 .

      - name: Run MyPy
        run: mypy .

  format:
    needs: lint
    if: success()  # Run only if lint job succeeds
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install formatting tools
        run: |
          python -m pip install --upgrade pip
          pip install black isort

      - name: Run Isort
        run: isort .

      - name: Run Black
        run: black .

      - name: Check for formatting changes
        id: check-diff
        run: |
          git diff --exit-code || echo "Formatting changes detected"
          if [ -n "$(git diff)" ]; then
            echo "changed=true" >> $GITHUB_ENV
          else
            echo "changed=false" >> $GITHUB_ENV
          fi

      - name: Push formatting changes back to PR branch
        if: env.changed == 'true'
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Auto-format code"
          git push origin HEAD:${{ github.head_ref }}

