name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Python
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # Install dependencies (including tools like isort, black, mypy, pytest)
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Run Black manually
    - name: Run Black
      run: |
        pip install black
        black .

    # Run Flake8
    - name: Run Flake8
      run: |
        pip install flake8
        flake8 .

    # Run Pylint
    - name: Run Pylint
      run: |
        pip install pylint
        pylint **/*.py

    # Run Pyright (Mypy)
    - name: Run Pyright
      run: |
        pip install pyright
        pyright

    # Run Pytest
    - name: Run Pytest
      run: |
        pip install pytest
        pytest
