name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Python
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # Install dependencies (including tools like isort, black, mypy, pytest)
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Use Microsoft's Python Action Collection for formatting and testing
    - name: Python Actions Collection
      uses: microsoft/action-python@0.7.2
      with:
        # Set the root directory
        root: .

        # Set Python version to 3.9
        python_version: '3.9'

        # Enable Black for formatting
        black: true

        # Enable Flake8 for formatting
        flake8: true

        # Enable Pylint for tpye checking
        pylint: true

        # Enable Pyright (for Mypy type checking)
        pyright: true

        # Enable Pytest for running unit tests
        pytest: true

    # Optionally, run isort separately if not included in the collection
    - name: Run isort
      run: |
        pip install isort
        isort .
