name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  auto-format:
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.create-branch.outputs.branch }}
    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3
      
      # Set up Python
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Install dependencies
      - name: Install pip
        run: |
          python -m pip install --upgrade pip

      # Run Black to format code
      - name: Run Black
        run: |
          pip install black
          black .

      # Check for formatting changes
      - name: Check for formatting changes
        id: git-status
        run: |
          git diff --exit-code || echo "Formatting changes detected"

      # Commit and push formatting changes to a new branch
      - name: Commit and push changes
        id: create-branch
        if: steps.git-status.outputs.changed == 'true'
        run: |
          BRANCH_NAME="formatting-branch-${{ github.run_id }}"
          git checkout -b $BRANCH_NAME
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Auto-format code"
          git push origin $BRANCH_NAME
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  lint-and-checks:
    needs: auto-format
    runs-on: ubuntu-latest
    if: needs.auto-format.outputs.branch != ''
    steps:
      # Checkout the formatted branch
      - name: Checkout formatted branch
        uses: actions/checkout@v3
        with:
          ref: ${{ needs.auto-format.outputs.branch }}

      # Set up Python
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run Flake8
      - name: Run Flake8
        run: |
          pip install flake8
          flake8 .

      # Run Pylint
      - name: Run Pylint
        run: |
          pip install pylint
          pylint **/*.py

      # Run Pyright (Mypy)
      - name: Run Pyright
        run: |
          pip install pyright
          pyright

      # Run Pytest
      - name: Run Pytest
        run: |
          pip install pytest
          pytest

  cleanup:
    needs: lint-and-checks
    runs-on: ubuntu-latest
    if: always()  # Ensures this job runs regardless of previous job outcomes
    steps:
      # Delete the temporary branch
      - name: Delete temporary branch
        run: |
          BRANCH_NAME="formatting-branch-${{ needs.auto-format.outputs.branch }}"
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git push origin --delete $BRANCH_NAME || true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
